name: CI

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]
  push:
    branches:
      - main
  schedule:
    - cron: "20 23 * * 4"

jobs:
  lint:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # windows-latest, # disabled as there are no fiona wheels on windows
          macos-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: x64
        if: matrix.os == 'macOS-latest'

      - name: Lint with rustfmt
        run: cargo fmt

      - name: Lint with clippy
        run: cargo clippy --all-targets

      - name: Install Python dependencies
        run: |
          pip install shapely geopandas

      - name: Test with cargo - default features
        run: cargo test --features test,wkb

      - name: Test with cargo - all features
        run: cargo test --all-features