name: CI

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]
  push:
    branches:
      - main
  schedule:
    - cron: "20 23 * * 4"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Lint with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Lint with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets

      - name: Install Python dependencies
        run: |
          pip install shapely geopandas

      - name: Test with cargo - default features
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          toolchain: stable
          args: --features test

      - name: Test with cargo - all features
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          toolchain: stable
          args: --all-features
